classdef ButtonPanel < handle
    %BUTTONPANEL Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        hParent
        
        hPanel        
        importButton
        saveButton
        setInfoButton
        exitButton
        analyzeButton
    end
    
    methods
        function obj = ButtonPanel(parentFig)
            obj.hParent = parentFig;
            obj.buildUI();
        end
        
        function buildUI(obj)
            obj.hPanel = uipanel(...
                'Parent', obj.hParent, ...
                'Title', 'Operations');
            
            mainLayout = uiextras.Grid(...
                'Parent', obj.hPanel, ...
                'Padding', 5);
            obj.importButton = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Import', ...
                'callback', @obj.import_button_callback);
            obj.saveButton = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Save');
            obj.setInfoButton = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Set', ...
                'callback', @obj.set_info_button_callback);
            obj.exitButton = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Exit');
            obj.analyzeButton = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'pushbutton', ...
                'String', 'Analyze');
            uiextras.Empty('Parent', mainLayout);
            uiextras.Empty('Parent', mainLayout);
            uiextras.Empty('Parent', mainLayout);
            uiextras.Empty('Parent', mainLayout);
            
            set(mainLayout, ...
                'RowSizes', [25 25 25], ...
                'ColumnSizes', [50 50 50], ...
                'Spacing', 5);
        end
        
        function import_button_callback(~, ~, ~)
            ManageView.dataImport();
        end
        
        function set_info_button_callback(~, ~, ~)
            SetInfoModule.SetInfoView(groot, ...
                Context.getInstance.getData('ProcessData'));
        end
    end
    
end

