classdef SetCurrentDataPanel < handle
    %SETCURRENTPANEL Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        hPanel
        hParent
        currentDataHandle
        controlObj
        
        userNameText
        locationText
        actionStateText
        leakDistText
        
        userNameEdit
        locationEdit
        actionStatePopup
        leakDistShow
    end
    
    properties(Dependent)
        userName
        location
        actionState
        leakDist
    end
    
    methods
        function obj = SetCurrentDataPanel(figParent, currentDataHandle)
            obj.hParent = figParent;
            obj.currentDataHandle = currentDataHandle;
            
            obj.buildUI();
            obj.controlObj = obj.makeController;
        end
        
        function buildUI(obj)
            obj.hPanel = uipanel(...
                'Parent', obj.hParent, ...
                'Title', 'Current Data', ...
                'Visible', 'off');
            
            mainLayout = uiextras.Grid(...
                'Parent', obj.hPanel, ...
                'Padding', 10);
            
            obj.userNameText = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'text', ...
                'String', 'User Name', ...
                'FontSize', 9);
            obj.locationText = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'text', ...
                'String', 'Location', ...
                'FontSize', 9);
            obj.actionStateText = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'text', ...
                'String', 'Action State', ...
                'FontSize', 9);
            obj.leakDistText = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'text', ...
                'String', 'Leak Distance', ...
                'FontSize', 9);
            
            obj.userNameEdit = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'edit');
            obj.locationEdit = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'edit');
            obj.actionStatePopup = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'popupmenu', ...
                'String', {'fixed', 'remained'});
            obj.leakDistShow = uicontrol(...
                'Parent', mainLayout, ...
                'Style', 'text', ...
                'String', '', ...
                'FontSize', 9);
            set(mainLayout, ...
                'RowSizes', [25 25 25 25], ...
                'ColumnSizes', [120 150], ...
                'Spacing', 5);
            set(obj.hPanel, 'Visible', 'on')
            obj.updateView();
        end
        
        function updateView(obj)
            set(obj.userNameEdit, 'String', ...
                obj.currentDataHandle.userName);
            set(obj.locationEdit, 'String', ...
                obj.currentDataHandle.location);
            set(obj.actionStatePopup, 'Value', ...
                obj.currentDataHandle.actionState);
            set(obj.leakDistShow, 'String', ...
                obj.currentDataHandle.leakDist)
        end
        
        function result = get.userName(obj)
            result = get(obj.userNameEdit, 'String');
        end
        function result = get.location(obj)
            result = get(obj.locationEdit, 'String');
        end
        function result = get.actionState(obj)
            result = get(obj.actionStatePopup, 'Value');
        end
        function result = get.leakDist(obj)
            result = get(obj.leakDistShow, 'String');
        end
        
        function controlObj = makeController(obj)
            controlObj = ...
                SetInfoModule.SetCurrentDataControl(obj, obj.currentDataHandle);
        end
        
    end
    
end

